version: '3.8' 
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python main.py'
    ports:
      - 8001:5000
      # - 8000:8000 
      # default port for Flask is 5000
      # 8000 is already Django app's port
    volumes:
      - .:/app # the current directory is /app directory in docker
    depends_on:
      - db # container db run 1st then backend container
  
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql # all file about db will be in dbdata in local machine, and in /var/lib/mysql in docker
    ports:
      - 33067:3306